---
- name: Install Docker and deploy n8n (secure cookie disabled, no volume)
  hosts: all
  become: true

  tasks:
    - name: Install required system packages
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
          - python3-pip
        state: present

    - name: Add Docker CE repository
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo

    - name: Install Docker
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Enable and start Docker service
      systemd:
        name: docker
        enabled: true
        state: started

    - name: Install Docker SDK for Python
      pip:
        name: docker

    - name: Stop and remove existing n8n container if any
      shell: |
        docker rm -f n8n || true
      ignore_errors: true

    - name: Remove existing n8n data directory (optional cleanup)
      file:
        path: /root/n8n-data
        state: absent

    - name: Pull n8n image
      docker_image:
        name: n8nio/n8n
        source: pull

    - name: Run n8n container using docker CLI (no volume, secure_cookie=false)
      shell: |
        docker run -d --name n8n \
          -p 5678:5678 \
          -e N8N_BASIC_AUTH_ACTIVE=true \
          -e N8N_BASIC_AUTH_USER=admin \
          -e N8N_BASIC_AUTH_PASSWORD=QWEqwe123 \
          -e N8N_HOST=0.0.0.0 \
          -e N8N_PORT=5678 \
          -e N8N_SECURE_COOKIE=false \
          n8nio/n8n:latest
      args:
        executable: /bin/bash
