- name: Install and Run MongoDB in Docker (RHEL)
  hosts: all
  become: true
  tasks:
    - name: Install required system packages for Docker
      yum:
        name:
          - docker
          - python3-pip
        state: present
      when: ansible_os_family == "RedHat"

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Install Docker SDK for Python
      pip:
        name: docker
        executable: pip3

    - name: Pull MongoDB image
      docker_image:
        name: mongo
        source: pull
      environment:
        DOCKER_HOST: unix:///var/run/docker.sock

    - name: Create MongoDB container
      docker_container:
        name: mongodb
        image: mongo:6
        state: started
        restart_policy: always
        published_ports:
          - "27017:27017"
        volumes:
          - /var/lib/mongo:/data/db
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: root
