- name: Install Docker CE and run MongoDB on RHEL 9
  hosts: all
  become: true
  tasks:

    - name: Remove podman and podman-docker
      yum:
        name:
          - podman
          - podman-docker
        state: absent

    - name: Add Docker CE repository
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo

    - name: Install Docker CE and pip3
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - python3-pip
        state: present

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Install Docker SDK for Python
      pip:
        name:
          - docker
          - requests
          - requests-unixsocket
        executable: pip3

    - name: Pull MongoDB image
      docker_image:
        name: mongo
        source: pull
      environment:
        DOCKER_HOST: unix:///var/run/docker.sock

    - name: Create MongoDB container
      docker_container:
        name: mongodb
        image: mongo:6
        state: started
        restart_policy: always
        published_ports:
          - "27017:27017"
        volumes:
          - /var/lib/mongo:/data/db
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: root
