---
- name: Install Docker and deploy n8n on RHEL
  hosts: all
  become: true

  tasks:
    - name: Install required system packages
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
          - python3-pip
        state: present

    - name: Add Docker CE repository
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo

    - name: Install Docker
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest

    - name: Enable and start Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Ensure docker group exists
      group:
        name: docker
        state: present

    - name: Add root user to docker group
      user:
        name: root
        groups: docker
        append: yes

    - name: Install Docker SDK for Python
      pip:
        name: docker
        executable: pip3

    - name: Pull n8n Docker image
      community.docker.docker_image:
        name: n8nio/n8n
        tag: latest
        source: pull

    - name: Run n8n container
      community.docker.docker_container:
        name: n8n
        image: n8nio/n8n:latest
        state: started
        restart_policy: always
        published_ports:
          - "5678:5678"
        env:
          N8N_BASIC_AUTH_ACTIVE: "true"
          N8N_BASIC_AUTH_USER: "admin"
          N8N_BASIC_AUTH_PASSWORD: "QWEqwe123"
