---
- name: Install Docker, Docker Compose, and Docker SDK
  hosts: all
  become: yes

  tasks:
    - name: Install required packages
      package:
        name:
          - yum-utils
          - curl
          - device-mapper-persistent-data
          - lvm2
          - python3
          - python3-pip
        state: present

    - name: Add Docker CE repo
      command: >
        dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
      args:
        creates: /etc/yum.repos.d/docker-ce.repo

    - name: Install Docker
      package:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest

    - name: Start and enable Docker
      service:
        name: docker
        enabled: yes
        state: started

    - name: Add current user to docker group
      user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: yes

    - name: Set permissions on docker.sock (DEV/TEST only)
      file:
        path: /var/run/docker.sock
        mode: '0666'

    - name: Install correct Docker Python SDK and dependencies
      pip:
        name:
          - docker>=6.1.3
          - requests
          - requests-unixsocket
        executable: pip3

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.24.6/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Verify Docker Compose version
      command: docker-compose --version
      register: compose_version
      changed_when: false

    - name: Show Docker Compose version
      debug:
        msg: "{{ compose_version.stdout }}"

    - name: Test Python Docker SDK access to Docker
      command: >
        python3 -c "import docker; client = docker.DockerClient(base_url='unix:///var/run/docker.sock'); print(client.version())"
      register: docker_sdk_test
      failed_when: docker_sdk_test.rc != 0
      changed_when: false

    - name: Show Docker SDK test result
      debug:
        msg: "{{ docker_sdk_test.stdout }}"
