---
- name: Fully Automated n8n Deployment on RHEL
  hosts: all
  become: yes
  vars:
    docker_repo_file: /etc/yum.repos.d/docker-ce.repo
    n8n_image: n8nio/n8n
    n8n_container_name: n8n
    n8n_data_dir: /opt/n8n/.n8n
    n8n_port: 5678
    n8n_env:
      TZ: Asia/Kuala_Lumpur
      N8N_BASIC_AUTH_ACTIVE: "true"
      N8N_BASIC_AUTH_USER: admin
      N8N_BASIC_AUTH_PASSWORD: strongpassword

  tasks:
    - name: Install required packages for Docker
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
          - curl
        state: present

    - name: Add Docker CE repo (if not exists)
      command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      args:
        creates: "{{ docker_repo_file }}"

    - name: Install Docker CE
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Enable and start Docker
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Install required Python packages for Docker SDK
      yum:
        name:
          - python3
          - python3-pip
        state: present

    - name: Install docker SDK for Python
      pip:
        name: docker
        executable: pip3

    - name: Ensure n8n data directory exists
      file:
        path: "{{ n8n_data_dir }}"
        state: directory
        owner: root
        mode: '0755'

    - name: Run n8n container
      community.docker.docker_container:
        name: "{{ n8n_container_name }}"
        image: "{{ n8n_image }}"
        state: started
        restart_policy: always
        ports:
          - "{{ n8n_port }}:5678"
        volumes:
          - "{{ n8n_data_dir }}:/home/node/.n8n"
        env: "{{ n8n_env }}"
