---
- name: Install Docker and deploy n8n on RHEL
  hosts: all
  become: yes
  vars:
    n8n_container_name: n8n
    n8n_image: n8nio/n8n:latest
    n8n_port: 5678
    n8n_data_dir: /opt/n8n/data
    n8n_env:
      - name: GENERIC_TIMEZONE
        value: Asia/Kuala_Lumpur
      - name: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - name: N8N_BASIC_AUTH_USER
        value: admin
      - name: N8N_BASIC_AUTH_PASSWORD
        value: strongpassword

  tasks:

    - name: Install required system packages
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
          - python3
          - python3-pip
        state: present

    - name: Add Docker CE repository
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo

    - name: Install Docker
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Enable and start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Ensure docker group exists
      group:
        name: docker
        state: present

    - name: Add root user to docker group
      user:
        name: root
        groups: docker
        append: yes

    - name: Install Docker SDK for Python
      pip:
        name: docker
        executable: pip3

    - name: Create n8n data directory
      file:
        path: "{{ n8n_data_dir }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Pull n8n Docker image
      community.docker.docker_image:
        name: "{{ n8n_image }}"

    - name: Run n8n container
      community.docker.docker_container:
        name: "{{ n8n_container_name }}"
        image: "{{ n8n_image }}"
        state: started
        restart_policy: always
        ports:
          - "{{ n8n_port }}:5678"
        volumes:
          - "{{ n8n_data_dir }}:/home/node/.n8n"
        env: "{{ n8n_env }}"
