---
- name: Setup Docker and run MongoDB container
  hosts: all
  become: yes

  vars:
    docker_compose_version: "v2.24.6"

  tasks:
    - name: Install required packages
      package:
        name:
          - yum-utils
          - curl
          - device-mapper-persistent-data
          - lvm2
          - python3
          - python3-pip
        state: present

    - name: Add Docker CE repo
      command: dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
      args:
        creates: /etc/yum.repos.d/docker-ce.repo

    - name: Install Docker
      package:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest

    - name: Start and enable Docker
      service:
        name: docker
        enabled: yes
        state: started

    - name: Add current user to docker group
      user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: yes

    - name: Set permissions on docker.sock (DEV/TEST only)
      file:
        path: /var/run/docker.sock
        mode: '0666'

    - name: Install Docker SDK for Python (future use)
      pip:
        name:
          - docker
          - requests
          - requests-unixsocket
        executable: pip3

    - name: Install Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-linux-x86_64"
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Run MongoDB container (named mongo-db)
      shell: |
        docker rm -f mongo-db || true
        docker run -d --name mongo-db -p 27017:27017 mongo:latest
      args:
        executable: /bin/bash
