- name: Install Docker and deploy n8n on RHEL
  hosts: all
  become: true

  tasks:
    - name: Install required packages
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
          - python3
          - python3-pip
        state: present

    - name: Add Docker CE repository
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo

    - name: Install Docker
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest

    - name: Enable and start Docker
      service:
        name: docker
        enabled: true
        state: started

    - name: Add root user to docker group
      user:
        name: root
        groups: docker
        append: yes

    - name: Stop and remove existing n8n container (if exists)
      shell: docker rm -f n8n || true
      ignore_errors: true

    - name: Remove existing n8n image (optional cleanup)
      shell: docker image rm n8nio/n8n:latest || true
      ignore_errors: true

    - name: Recreate n8n data directory
      file:
        path: /root/n8n-data
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Pull latest n8n image
      shell: docker pull n8nio/n8n:latest

    - name: Run n8n container
      shell: |
        docker run -d --name n8n \
          -p 5678:5678 \
          -v /root/n8n-data:/home/node/.n8n \
          -e N8N_BASIC_AUTH_ACTIVE=true \
          -e N8N_BASIC_AUTH_USER=admin@gg.com \
          -e N8N_BASIC_AUTH_PASSWORD=QWEqwe123 \
          -e N8N_HOST=0.0.0.0 \
          -e N8N_PORT=5678 \
          -e N8N_SECURE_COOKIE=false \
          -e N8N_DIAGNOSTICS_ENABLED=false \
          -e N8N_VERSION_NOTIFICATIONS_ENABLED=false \
          -e N8N_PERSONALIZATION_ENABLED=false \
          -e N8N_AUTH_EXCLUDE_ENDPOINTS="" \
          -e N8N_DISABLE_PRODUCTION_MAIN_MENU=true \
          -e N8N_SKIP_WEBHOOK_DEREGISTRATION_SHUTDOWN=true \
          n8nio/n8n:latest
      args:
        executable: /bin/bash
